### ISSUE TITLE
Changing parameters does not change computation time

### ISSUE THREAD

**Issue by rogerssam** [wrathematics/argon2#1]
Hi,
Thanks very much for your work on this implementation! I have been testing it, and noticed that changing the parameters does not seem to substantially change the computation time. Is this expected behaviour? My understanding was that changing these parameters would change (increase) computation time.

```
devtools::install_github("wrathematics/argon2")
library(microbenchmark)
library(argon2)

microbenchmark(
    default = pw_hash("a password"),
    variant = pw_hash("a password", variant = 'd'),
    iterations = pw_hash("a password", iterations = 10000),
    memory = pw_hash("a password", memory = 1024),
    all = pw_hash("a password", variant = 'd', iterations = 10000, memory = 1024)
)

Unit: milliseconds
       expr      min       lq     mean   median       uq      max neval cld
    default 190.9841 203.0847 216.5291 210.2230 220.2377 353.9675   100   b
    variant 192.0978 198.6971 209.5122 204.1203 215.6301 263.4297   100  a 
 iterations 193.2640 203.4037 214.3865 212.2671 221.0665 269.6673   100  ab
     memory 191.2473 202.5132 214.4438 211.3126 222.7747 267.7695   100  ab
        all 190.0364 200.2290 211.7794 206.4909 220.4166 252.5742   100  ab
```

**Comment by wrathematics** [comment]
Hey sorry I'm a few years (!) late on this. Using the latest version and changing the number of iterations to 100, I see

```
Unit: milliseconds
       expr         min          lq       mean      median          uq
    default    63.20544    64.11737    65.6284    66.23945    66.85655
    variant    63.27593    64.43699    64.9502    64.92210    65.53350
 iterations   402.08908   405.33151   408.0295   408.36480   408.78131
     memory  6190.30509  6195.64805  6229.4240  6230.07319  6245.99975
        all 37174.82608 37202.85839 37281.5796 37287.53350 37317.95812
         max neval
    67.72321     5
    66.58250     5
   415.58072     5
  6285.09367     5
 37424.72172     5
```

I tried an older version, and I saw similar runtime differences. Not sure why you saw such similar runtimes. Just curious, what OS are/were you on?

**Comment by rogerssam** [comment]
Thanks for getting back to me! I had completely forgotten about this.
I expect I was running this on Windows 10, but will check again with the latest version on at least Windows and Ubuntu.

**Comment by rogerssam** [comment]
Hi again,
I just ran this again on my Windows laptop with the latest version, and get similar results to you above. So perhaps it was a quirk with my previous install or the previous version? I will still investigate on my other machines but happy for you to close this now :)

**Comment by wrathematics** [comment]
Thanks for checking. I appreciate it. No need to waste a lot of time on this, but if you can recreate the issue, I'll try to fix it.

**Comment by rogerssam** [comment]
Hi again Drew,
I have run this on my work computer which was where I originally experienced the issue (I think!). Can confirm that this is no longer an issue. I'm not even sure how I created it now, as my work computer was running version 0.2.0 which didn't have the extra parameters exposed, and I couldn't replicate the error on version 0.3.0. I'll close it and put it down to some rookie mistake by me :)
